### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by deepseek** [visiont3lab/text_recognition#1]
@visiont3lab Thank you for your hard work,

What about the training code

**Comment by visiont3lab** [comment]
Hi @deepseek, many thanks for youe interest!
Actually we use trained models from CRAFT project (for both: text detection and OCR). Have a look at their page.

**Comment by deepseek** [comment]
Thanks

**Comment by deepseek** [comment]
@visiont3lab Though bare in mind that training is very important
